### ISSUE TITLE
Code maat extensions

### ISSUE THREAD

**Issue by psrijay** [adamtornhill/code-maat#67]
Hi adamtornhill
Wanted to know whether all scenarios of code-forensics are covered here like sloc,churn etc if not what are to be covered and when are you going to extend it.How many languages it supports currently 
and how to extend it for other languages.Wanted to know how to extend in terms of code.

**Comment by adamtornhill** [comment]
Hi @psrijay 

Code Maat is the engine for code-forensics, so all evolutionary metrics come from here. Code Maat doesn't include a sloc calculation itself, but relies on external tooling like `cloc`. Hence, all analyses in Code Maat are language neutral.

I'm still maintaining Code Maat since it has quite a wide user base. That said, the tool is stable and I don't actively expand the analysis set. 
Instead, I dedicate my time to [CodeScene](https://codescene.io/). CodeScene represents the evolution of these analyses. CodeScene also introduces language-specific analyses like X-Ray (function level analyses), Code Health trends, and Pull Request integrations. It's free for open source and education, and I hope you find it interesting.
