### ISSUE TITLE
Extension and Support

### ISSUE THREAD

**Issue by kpsamuel** [adamtornhill/code-maat#69]
Hi @adamtornhill ,

I loved this tool and learning to understand more to use code-maat in my work environment. I want to know still what new features are you going to add up and how support will be delivered if i looking it to deploy it in my working place.

**Comment by kpsamuel** [comment]
any updates, please confirm.

**Comment by adamtornhill** [comment]
Hi @kpsamuel 

Thanks, I'm happy to hear that you love the tool. 

I open sourced Code Maat as a way of making the techniques from Your Code as a Crime Scene accessible to the community. I'm still maintaining Code Maat since it has quite a wide user base, but I don't actively expand the analysis set. Since it's a free project, I do the maintenance when I have time for it and there isn't any formal support.

If you're looking for a professional tool with support, then I recommend that you check out [CodeScene by Empear](https://empear.com/). CodeScene represents the evolution of these analyses and is actively developed by a team. CodeScene also introduces language-specific analyses like X-Ray (function level analyses), user management, Code Health trends, Pull Request integrations, Jira integration, reporting, and much more. It's free for open source and education, and I hope you find CodeScene interesting.

**Comment by kpsamuel** [comment]
can we setup a call, i want to understand the logic of working in code maat and code scene. i used code scene but not understanding the logic of calculation.

**Comment by prajeeshkozhisseri** [comment]
we are looking at to add this to our project on codescene. We like to understand on some components like  Architectural   Analyses, CodeHealth   - Biomarkers so that we can really looking at adding to  our projects

**Comment by adamtornhill** [comment]
@kpsamuel and @prajeeshkozhisseri  Sure, the CodeScene team can help you on this (code-maat is not the right forum, unfortunately). May I ask you to email support@empear.com with your CodeScene specific requests and questions?

I also have a blog post that covers the key technical metrics in CodeScene, including code health: [Measure the Health of your Codebase](https://www.linkedin.com/pulse/measure-health-your-codebase-adam-tornhill/)
