### ISSUE TITLE
Question: any plans to support --temporal-period with values other than "1"?

### ISSUE THREAD

**Issue by StefanSmith** [adamtornhill/code-maat#84]
Are there any plans to support `--temporal-period` with values other than `1`? I'm analysing temporal coupling across repositories and suspect the temporally-coupled commits may be distributed across multiple days.

Thank you for all your great work in this space!

**Comment by adamtornhill** [comment]
That's definitely a possible extension. I can take a look at it during next week. Ideally, we'd add a command line argument which lets you modify the temporal period.

**Comment by adamtornhill** [comment]
@StefanSmith I took a look at this during the weekend, and there was indeed a `TODO` in the code on this feature. Took the time to implement an arbitrary `--temporal-period` so that you can calculate coupling over multiple days (rolling).

You find this improvement in the latest release: https://github.com/adamtornhill/code-maat/releases/tag/v1.0.3

Please let me know how this works out for you.

**Comment by StefanSmith** [comment]
Thank you @adamtornhill ! I'm away this week but will take a look next week. You may want to update the details in the README here: https://github.com/adamtornhill/code-maat#temporal-periods

**Comment by StefanSmith** [comment]
Finally got round to verifying the change. Thanks @adamtornhill, it works as expected. I've integrated it into my pet project at https://github.com/StefanSmith/your-code-as-a-crime-scene-tools. In reality, I'm finding that multi-day coupling analysis pulls in too many false positives due to the high rate of (unrelated) commits occuring across multiple repositories. I will investigate using commit messages instead to gather commits with common story numbers.

**Comment by StefanSmith** [comment]
As a follow up to this, does `code-maat` support coupling analysis using commit message regex to group commits (e.g by story numbers)?
